### ISSUE TITLE
Do not request resource from classloader using path with leading slash

### ISSUE THREAD

**Issue by Vyacheslav-Lapin** [JetBrains/spotbugs-intellij-plugin#66] opened 2021-02-11 18:10 UTC
The error was copied to the clipboard. Press Command+V
Product Infos
    SpotBugs: 4.1.3
    IntelliJ SpotBugs plugin: 1.2.4
    IDEA: IntelliJ IDEA 2021.1 EAP
    IDEA-Build: IU-211.5787.15, February 10, 2021
    JRE: 11.0.10+9-b1319.6 x86_64
    JVM: Dynamic Code Evolution 64-Bit Server VM JetBrains s.r.o.

Do not request resource from classloader using path with leading slash
java.lang.IllegalArgumentException: /messages_en_GB.xml
	at com.intellij.util.lang.UrlClassLoader.findResource(UrlClassLoader.java:283)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:391)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:373)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
	at edu.umd.cs.findbugs.PluginLoader.getResource(PluginLoader.java:560)
	at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1279)
	at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
	at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
	at edu.umd.cs.findbugs.PluginLoader.<init>(PluginLoader.java:395)
	at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
	at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
	at edu.umd.cs.findbugs.PluginLoader.<clinit>(PluginLoader.java:149)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:85)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.compute(WithPluginClassloader.java:46)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:82)
	at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:72)
	at org.jetbrains.plugins.spotbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.load(PluginTablePane.java:280)
	at org.jetbrains.plugins.spotbugs.gui.settings.PluginTablePane.reset(PluginTablePane.java:274)
	at org.jetbrains.plugins.spotbugs.gui.settings.GeneralTab.reset(GeneralTab.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.SettingsPane.reset(SettingsPane.java:169)
	at org.jetbrains.plugins.spotbugs.gui.settings.AbstractConfigurableImpl.reset(AbstractConfigurableImpl.java:94)
	at org.jetbrains.plugins.spotbugs.gui.settings.ModuleConfigurableImpl.reset(ModuleConfigurableImpl.java:57)
	at com.intellij.openapi.roots.ui.configuration.ModuleConfigurableWrapper.reset(ModuleConfigurableWrapper.java:58)
	at com.intellij.openapi.roots.ui.configuration.TabbedModuleEditor.createCenterPanel(TabbedModuleEditor.java:63)
	at com.intellij.openapi.roots.ui.configuration.HeaderHidingTabbedModuleEditor.createCenterPanel(HeaderHidingTabbedModuleEditor.java:30)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.createPanel(ModuleEditor.java:250)
	at com.intellij.openapi.roots.ui.configuration.ModuleEditor.getPanel(ModuleEditor.java:262)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleConfigurable.createOptionsPanel(ModuleConfigurable.java:122)
	at com.intellij.openapi.ui.NamedConfigurable.createComponent(NamedConfigurable.java:73)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelection(MasterDetailsComponent.java:596)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.updateSelection(ModuleStructureConfigurable.java:196)
	at com.intellij.openapi.ui.MasterDetailsComponent.setSelectedNode(MasterDetailsComponent.java:587)
	at com.intellij.openapi.ui.MasterDetailsComponent.updateSelectionFromTree(MasterDetailsComponent.java:225)
	at com.intellij.openapi.ui.MasterDetailsComponent.createComponent(MasterDetailsComponent.java:279)
	at com.intellij.openapi.roots.ui.configuration.projectRoot.ModuleStructureConfigurable.createComponent(ModuleStructureConfigurable.java:419)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.navigateTo(ProjectStructureConfigurable.java:494)
	at com.intellij.openapi.roots.ui.configuration.ProjectStructureConfigurable.reset(ProjectStructureConfigurable.java:344)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:56)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:78)
	at com.intellij.openapi.options.ex.SingleConfigurableEditor.<init>(SingleConfigurableEditor.java:93)
	at com.intellij.ide.actions.ShowStructureSettingsAction$1.<init>(ShowStructureSettingsAction.java:40)
	at com.intellij.ide.actions.ShowStructureSettingsAction.showDialog(ShowStructureSettingsAction.java:40)
	at com.intellij.ide.actions.ShowStructureSettingsAction.actionPerformed(ShowStructureSettingsAction.java:36)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:269)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:269)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:676)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:626)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:486)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:481)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:232)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:888)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:832)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:448)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:782)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by jqyp** [comment] 2021-03-19 18:38
@Vyacheslav-Lapin, sorry for the long wait! The problem isn't on the plugin side but on the IntelliJ IDEA side.
I will follow the situation closely and write you when the problem is fixed. Now I can only advise you to use not IntelliJ IDEA EAP but a stable version.

**Comment by jqyp** [comment] 2021-03-25 14:05
The bug is fixed in IntelliJ IDEA 2021.1 Beta 4.

**Closed by jqyp** 2021-03-25 14:05 UTC

**Comment by bml-axon** [comment] 2021-08-17 13:28
I see this same problem in IntelliJ IDEA 2021.2 Build #IU-212.4746.92

**Comment by kevin-wayne** [comment] 2021-08-25 10:28
Experiencing the same problem in IntelliJ IDEA 2021.2.1 Build #IC-212.5080.55, which is the latest stable version. Worked fine in 2021.1.

**Comment by shubz1998** [comment] 2021-09-27 18:17
Seeing the same in IDEA 2021.2.2 Build #IC-212.5284.40.

**Comment by Lord-Haji** [comment] 2021-11-22 13:07
Seeing the same in #IC-212.5457.46
